### ISSUE TITLE
<class 'struct.error'>: unpack requires a buffer of 2 bytes

### ISSUE THREAD

**Issue by Pitr2** [jmplonka/Importer3D#9]
I'm trying to import a .GSM file into FreeCAD, but I get the following error:

16:33:56  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\FreeCAD 0.19\Mod\Importer3D-master\importer3D.py", line 60, in open
    read(doc, filename)
  File "C:\Program Files\FreeCAD 0.19\Mod\Importer3D-master\importer3D.py", line 35, in read
    importGSM.read(doc, filename)
  File "C:\Program Files\FreeCAD 0.19\Mod\Importer3D-master\importGSM.py", line 433, in read
    block = readGsmBlock(data, bHdr)
  File "C:\Program Files\FreeCAD 0.19\Mod\Importer3D-master\importGSM.py", line 151, in readGsmBlock
    if (bHdr.key == 'CSD3'): return GsmCsd3(data, bHdr)
  File "C:\Program Files\FreeCAD 0.19\Mod\Importer3D-master\importGSM.py", line 46, in __init__
    GsmBlock.__init__(self, data, bHdr)
  File "C:\Program Files\FreeCAD 0.19\Mod\Importer3D-master\importGSM.py", line 34, in __init__
    self.subKey, self.pos  = getShort(data, self.pos + 2)
  File "C:\Program Files\FreeCAD 0.19\Mod\Importer3D-master\importUtils.py", line 73, in getShort
    def getShort(data, offset): return _get(data, 'H', 2, offset)
  File "C:\Program Files\FreeCAD 0.19\Mod\Importer3D-master\importUtils.py", line 63, in _get
    value, = unpack(ENDIANNESS + fmt, data[offset:end])
<class 'struct.error'>: unpack requires a buffer of 2 bytes

I've searched the error but could not find a suitable solution for this situation.
Thank you for your work.

**Comment by jmplonka** [comment]
Please, could you share an example?

**Comment by Pitr2** [comment]
Hello, you mean an example file?

**Comment by jmplonka** [comment]
Hello Pietro, any GSM file so I can reproduce the error.

**Comment by Pitr2** [comment]
Ok, the error is gone. Thank you very much!
